### ISSUE TITLE
next update LOS 18?

### ISSUE THREAD

**Issue by zedocrob** [los-legacy/Troubleshooting#1]
Hi,nice trick but what will happen after flashing next update for LOS 18? Is Fakestore will be back and playstore (phonesky) gone?
Do we have to do the procedure after each LOS 18 updates?

**Comment by Exodusnick** [comment]
No, the procedure must be used only once.

**Comment by zedocrob** [comment]
Thanks, Do you think it should also work with OrangeFox 11 recovery?

**Comment by daywalk3r666** [comment]
Sure. These are magisk modules. this have nothing to do with the recovery

**Comment by BenJule** [comment]
Please use our Community: https://forum.los-legacy.de eg: Q&A
